Repository googleapis/nodejs-vision, pull requests merged in 2019-05, with the labels that each got.

#364 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#363 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#365 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#373 test: fix broken sample tests
  samples/system-test/detect.v1p1beta1.test.js
  samples/system-test/importProductSets.test.js
Labels: cla: yes

#369 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
  package.json
Labels: cla: yes

#370 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#371 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#360 chore: update formatting for generated code
  src/v1/product_search_client.js
  src/v1p3beta1/product_search_client.js
  src/v1p4beta1/product_search_client.js
  synth.metadata
  test/gapic-v1.js
Labels: :rotating_light:, cla: yes

#375 feat: image annotation batching
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  protos/google/cloud/vision/v1/geometry.proto
  protos/google/cloud/vision/v1/image_annotator.proto
  protos/google/cloud/vision/v1/product_search.proto
  protos/google/cloud/vision/v1/product_search_service.proto
  protos/google/cloud/vision/v1/text_annotation.proto
  protos/google/cloud/vision/v1/web_detection.proto
  src/v1/doc/google/cloud/vision/v1/doc_image_annotator.js
  src/v1/doc/google/cloud/vision/v1/doc_product_search.js
  src/v1/doc/google/cloud/vision/v1/doc_product_search_service.js
  src/v1/doc/google/cloud/vision/v1/doc_web_detection.js
  src/v1/image_annotator_client.js
  src/v1/image_annotator_client_config.json
  src/v1/index.js
  src/v1/product_search_client.js
  src/v1/product_search_client_config.json
  src/v1p1beta1/image_annotator_client_config.json
  src/v1p2beta1/image_annotator_client_config.json
  src/v1p3beta1/image_annotator_client_config.json
  src/v1p3beta1/product_search_client_config.json
  src/v1p4beta1/image_annotator_client_config.json
  src/v1p4beta1/product_search_client_config.json
  synth.metadata
  test/gapic-v1.js
Labels: cla: yes

#377 fix: DEADLINE_EXCEEDED is idempotent
  src/v1/image_annotator_client_config.json
  src/v1/product_search_client_config.json
  src/v1p1beta1/image_annotator_client_config.json
  src/v1p2beta1/image_annotator_client_config.json
  src/v1p3beta1/image_annotator_client_config.json
  src/v1p3beta1/product_search_client_config.json
  src/v1p4beta1/image_annotator_client_config.json
  src/v1p4beta1/product_search_client_config.json
  synth.metadata
Labels: cla: yes

#378 docs: update jsdoc comments
  protos/google/cloud/vision/v1/image_annotator.proto
  src/v1/doc/google/cloud/vision/v1/doc_image_annotator.js
  synth.metadata
Labels: cla: yes

#380 chore: release 1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#382 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/test.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  protos/google/cloud/vision/v1/product_search.proto
  protos/google/cloud/vision/v1/product_search_service.proto
  protos/google/cloud/vision/v1p4beta1/product_search.proto
  protos/google/cloud/vision/v1p4beta1/product_search_service.proto
  src/v1/doc/google/cloud/vision/v1/doc_product_search.js
  src/v1/doc/google/cloud/vision/v1/doc_product_search_service.js
  src/v1p4beta1/doc/google/cloud/vision/v1p4beta1/doc_product_search.js
  src/v1p4beta1/doc/google/cloud/vision/v1p4beta1/doc_product_search_service.js
  synth.metadata
Labels: cla: yes

#384 refactor: drop dependency on lodash.merge and update links
  package.json
  src/v1/image_annotator_client.js
  src/v1/product_search_client.js
  src/v1p1beta1/image_annotator_client.js
  src/v1p2beta1/image_annotator_client.js
  src/v1p3beta1/image_annotator_client.js
  src/v1p3beta1/product_search_client.js
  src/v1p4beta1/image_annotator_client.js
  src/v1p4beta1/product_search_client.js
  synth.metadata
Labels: cla: yes

#385 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#386 build: start auto publishing docs to googleapis.dev
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#387 docs: expand documentation on product descriptions
  protos/google/cloud/vision/v1/product_search.proto
  protos/google/cloud/vision/v1/product_search_service.proto
  protos/google/cloud/vision/v1p4beta1/product_search.proto
  protos/google/cloud/vision/v1p4beta1/product_search_service.proto
  src/v1/doc/google/cloud/vision/v1/doc_product_search.js
  src/v1/doc/google/cloud/vision/v1/doc_product_search_service.js
  src/v1p4beta1/doc/google/cloud/vision/v1p4beta1/doc_product_search.js
  src/v1p4beta1/doc/google/cloud/vision/v1p4beta1/doc_product_search_service.js
  synth.metadata
Labels: cla: yes

#388 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#389 build: use repo metadata to generate the readme
  .cloud-repo-tools.json
  .gitignore
  .repo-metadata.json
  README.md
  package.json
  samples/README.md
  synth.metadata
Labels: cla: yes

#390 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
