Repository googleapis/nodejs-vision, pull requests merged in 2019-09, with the labels that each got.

#433 test(samples): make detect assertions less specific
  samples/system-test/detect.test.js
Labels: cla: yes

#428 fix: use process versions object for client header
  README.md
  protos/protos.json
  src/service_proto_list.json
  src/v1/doc/google/protobuf/doc_timestamp.js
  src/v1/image_annotator_client.js
  src/v1/product_search_client.js
  src/v1p1beta1/image_annotator_client.js
  src/v1p2beta1/image_annotator_client.js
  src/v1p3beta1/doc/google/protobuf/doc_timestamp.js
  src/v1p3beta1/image_annotator_client.js
  src/v1p3beta1/product_search_client.js
  src/v1p4beta1/doc/google/protobuf/doc_timestamp.js
  src/v1p4beta1/image_annotator_client.js
  src/v1p4beta1/product_search_client.js
  synth.metadata
  synth.py
Labels: cla: yes

#436 fix(samples): upgrade yargs and fix broken CLI config
  samples/package.json
  samples/system-test/detect.v1p3beta1.test.js
Labels: cla: yes

#435 feat: update to gax with http2 fallback
  protos/protos.json
  src/browser.js
  src/v1/image_annotator_client.js
  src/v1/image_annotator_proto_list.json
  src/v1/product_search_client.js
  src/v1/product_search_proto_list.json
  src/v1p1beta1/image_annotator_client.js
  src/v1p1beta1/image_annotator_proto_list.json
  src/v1p2beta1/image_annotator_client.js
  src/v1p2beta1/image_annotator_proto_list.json
  src/v1p3beta1/image_annotator_client.js
  src/v1p3beta1/image_annotator_proto_list.json
  src/v1p3beta1/product_search_client.js
  src/v1p3beta1/product_search_proto_list.json
  src/v1p4beta1/image_annotator_client.js
  src/v1p4beta1/image_annotator_proto_list.json
  src/v1p4beta1/product_search_client.js
  src/v1p4beta1/product_search_proto_list.json
  synth.metadata
  test/gapic-v1.js
  test/gapic-v1p1beta1.js
  test/gapic-v1p2beta1.js
  test/gapic-v1p3beta1.js
  test/gapic-v1p4beta1.js
  webpack.config.js
Labels: cla: yes, kokoro:force-run

#438 chore: remove conformance tests from .nycrc
  .nycrc
Labels: cla: yes

#437 chore: release 1.3.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#440 docs: updates comments in protos
  protos/google/cloud/vision/v1/product_search.proto
  protos/google/cloud/vision/v1/product_search_service.proto
  protos/google/cloud/vision/v1p4beta1/product_search.proto
  protos/google/cloud/vision/v1p4beta1/product_search_service.proto
  src/v1/doc/google/cloud/vision/v1/doc_product_search.js
  src/v1/doc/google/cloud/vision/v1/doc_product_search_service.js
  src/v1p4beta1/doc/google/cloud/vision/v1p4beta1/doc_product_search.js
  src/v1p4beta1/doc/google/cloud/vision/v1p4beta1/doc_product_search_service.js
  synth.metadata
Labels: cla: yes

#441 feat: make vision helpers work with JSON proto
  package.json
  src/helpers.js
Labels: cla: yes

#442 chore: release 1.4.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#444 feat: additional safe search confidence fields
  protos/google/cloud/vision/v1/image_annotator.proto
  protos/google/cloud/vision/v1/product_search.proto
  protos/google/cloud/vision/v1/product_search_service.proto
  protos/google/cloud/vision/v1/text_annotation.proto
  protos/protos.json
  src/v1/doc/google/cloud/vision/v1/doc_image_annotator.js
  src/v1/doc/google/cloud/vision/v1/doc_product_search.js
  src/v1/doc/google/cloud/vision/v1/doc_product_search_service.js
  src/v1/doc/google/cloud/vision/v1/doc_text_annotation.js
  src/v1/image_annotator_client.js
  src/v1/product_search_client.js
  synth.metadata
Labels: cla: yes

#429 docs(samples): purge products
  samples/productSearch/productSets.js
  samples/productSearch/products.js
  samples/system-test/detect.test.js
  samples/system-test/productSets.test.js
  samples/system-test/products.test.js
Labels: cla: yes

#453 chore: update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla: yes

#454 tests: fixture resources have moved
  samples/system-test/referenceImages.test.js
  samples/system-test/similarProducts.test.js
Labels: cla: yes

#452 chore: add protos/ to .eslintignore
  .eslintignore
Labels: cla: yes
