Repository googleapis/nodejs-vision, pull requests merged in 2020-10, with the labels that each got.

#829 chore: update bucket for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#830 build(node_library): migrate to Trampoline V2
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  synth.metadata
Labels: api: vision, automerge: exact, cla: yes, context: full

#836 build: only check --engine-strict for production deps
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#837 chore: clean up Node.js TOC for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#838 docs(samples): modernize the samples
  samples/.eslintrc.yml
  samples/async-batch-annotate-images.js
  samples/batch-annotate-files-gcs.js
  samples/batch-annotate-files.js
  samples/detect.v1p3beta1.js
  samples/package.json
  samples/productSearch/addProductToProductSet.js
  samples/productSearch/createProduct.js
  samples/productSearch/createProductSet.js
  samples/productSearch/createReferenceImage.js
  samples/productSearch/deleteProduct.js
  samples/productSearch/deleteProductSet.js
  samples/productSearch/deleteReferenceImage.js
  samples/productSearch/getProduct.js
  samples/productSearch/getProductSet.js
  samples/productSearch/getReferenceImage.js
  samples/productSearch/getSimilarProducts.js
  samples/productSearch/getSimilarProductsGcs.js
  samples/productSearch/importProductSets.js
  samples/productSearch/listProductSets.js
  samples/productSearch/listProducts.js
  samples/productSearch/listProductsInProductSet.js
  samples/productSearch/listReferenceImage.js
  samples/productSearch/purgeOrphanProducts.js
  samples/productSearch/purgeProductsInProductSet.js
  samples/productSearch/removeProductFromProductSet.js
  samples/productSearch/template.js
  samples/productSearch/updateProductLabels.js
  samples/quickstart.js
  samples/setEndpoint.js
  samples/textDetection.js
  samples/vision-face-detection.js
Labels: cla: yes

#843 docs: updated code of conduct (includes update to actions)
  .github/workflows/ci.yaml
  CODE_OF_CONDUCT.md
  README.md
  samples/README.md
  synth.metadata
Labels: automerge, cla: yes, context: partial
