Repository googleapis/nodejs-vision, pull requests merged in 2020-07, with the labels that each got.

#798 build: use bazel build
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#799 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#802 build: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#805 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#806 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  synth.metadata
Labels: automerge, cla: yes, context: none

#809 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#807 build: missing parenthesis in publish script, delete Node 8 tests, add config for cloud-rad for nodejs
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: cla: yes, context: partial

#811 build: rename __toc to toc, move gitattributes files to node templates
  .gitattributes
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: cla: yes, context: full
