Repository googleapis/nodejs-vision, pull requests merged in 2020-11, with the labels that each got.

#844 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#845 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v1/image_annotator_client.ts
  src/v1/product_search_client.ts
  src/v1p1beta1/image_annotator_client.ts
  src/v1p2beta1/image_annotator_client.ts
  src/v1p3beta1/image_annotator_client.ts
  src/v1p3beta1/product_search_client.ts
  src/v1p4beta1/image_annotator_client.ts
  src/v1p4beta1/product_search_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: vision, automerge, cla: yes

#847 fix(browser): check for fetch on window
  protos/protos.json
  src/v1/image_annotator_client.ts
  src/v1/product_search_client.ts
  src/v1p1beta1/image_annotator_client.ts
  src/v1p2beta1/image_annotator_client.ts
  src/v1p3beta1/image_annotator_client.ts
  src/v1p3beta1/product_search_client.ts
  src/v1p4beta1/image_annotator_client.ts
  src/v1p4beta1/product_search_client.ts
  synth.metadata
Labels: api: vision, cla: yes, context: none

#849 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full
